version: '3'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    volumes:
      - ./backend/:/app
  
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd123
      - POSTGRES_DB=sss
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: