FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build-env
WORKDIR /app

COPY /Software.Specification.Builder/*.csproj ./
RUN dotnet restore

COPY /Software.Specification.Builder/ .

CMD ["dotnet", "watch", "run", "--project", "Software.Specification.Builder.csproj"]