FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build-env

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

# Install unzip for remote debugger
RUN apt-get update
RUN apt-get install unzip

WORKDIR /app

COPY ["./Software Specification Builder.sln", "./"]
COPY ./API/API.csproj ./API/API.csproj
COPY ./API/Directory.Build.props ./API/
COPY ./Persistence/Persistence.csproj ./Persistence/Persistence.csproj
COPY ./API.Tests.Integration/API.Tests.Integration.csproj ./API.Tests.Integration/API.Tests.Integration.csproj

RUN dotnet restore

COPY . .

CMD ["dotnet", "watch", "--project", "API", "run"]